print("hello'mirahihihi")
print("hello \nworld")
print("hello\tworld")
s = len("hello")
print(s)
mystring = "Hello World"
print(mystring[2:])
print(mystring[-2])
print(mystring[:3])
print(mystring[3:8])
print(mystring[::])
print(mystring[::2])
print(mystring[2:8:2])
#[start:stop:step]
print(mystring[::-1])